FROM nvidia/opengl:1.2-glvnd-devel-ubuntu20.04

RUN :\
    && apt-get update -q \
    && export DEBIAN_FRONTEND=nointeractive \
    && apt-get install -y --no-install-recommends \
        vim tar xz-utils curl git build-essential \
        libx11-6 libxcb1 libxau6 libgl1-mesa-dev \
        xvfb dbus-x11 x11-utils libxkbcommon-x11-0 \
        libavcodec-dev libavformat-dev libswscale-dev \
        python3 python3-dev python3-virtualenv \
        libraw1394-11 libmpfr6 \
        libusb-1.0-0 \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN git config --global http.sslVerify false

RUN :\
    && groupadd -g 1000 randuser \
    && useradd -d /home/randuser -s /bin/bash -m randuser -u 1000 -g 1000

USER randuser

ENV HOME /home/randuser

RUN :\
    && curl -o ${HOME}/coppeliasim.tar.xz https://downloads.coppeliarobotics.com/V4_1_0/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04.tar.xz \
    && tar -xvf ${HOME}/coppeliasim.tar.xz -C ${HOME} \
    && rm ${HOME}/coppeliasim.tar.xz \
    && :

ENV COPPELIASIM_ROOT=${HOME}/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${COPPELIASIM_ROOT}
ENV QT_QPA_PLATFORM_PLUGIN_PATH=${COPPELIASIM_ROOT}

RUN :\
    && cd ${HOME} \
    && virtualenv venv && . venv/bin/activate \
    && git clone https://github.com/stepjam/PyRep.git ${HOME}/pyrep && cd pyrep \
    && git checkout 4.1.0 \
    && pip install -r requirements.txt \
    && pip install . \
    && :

RUN :\
    && cd ${HOME} \
    && . venv/bin/activate \
    && git clone https://github.com/stepjam/RLBench.git ${HOME}/rlbench && cd rlbench \
    && git checkout 7c3f425f4a0b6b5ce001ba7246354eb3c70555be \
    && pip install -r requirements.txt \
    && pip install . \
    && :

WORKDIR ${HOME}/colosseum

USER root

RUN chown -R randuser:randuser ${HOME}/colosseum
RUN chmod 755 ${HOME}/colosseum

USER randuser

COPY --chown=randuser:randuser . .

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

RUN :\
    && cd ${HOME} \
    && . venv/bin/activate \
    && cd ${HOME}/colosseum \
    && pip install -r requirements.txt \
    && pip install -e . \
    && mkdir /tmp/rlbench_data \
    && :
