from colosseum.rlbench.tasks.basketball_in_hoop import BasketballInHoop
from colosseum.rlbench.tasks.close_box import CloseBox
from colosseum.rlbench.tasks.close_laptop_lid import CloseLaptopLid
from colosseum.rlbench.tasks.empty_dishwasher import EmptyDishwasher
from colosseum.rlbench.tasks.get_ice_from_fridge import GetIceFromFridge
from colosseum.rlbench.tasks.hockey import Hockey
from colosseum.rlbench.tasks.insert_onto_square_peg import InsertOntoSquarePeg
from colosseum.rlbench.tasks.meat_on_grill import MeatOnGrill
from colosseum.rlbench.tasks.move_hanger import MoveHanger
from colosseum.rlbench.tasks.open_drawer import OpenDrawer
from colosseum.rlbench.tasks.place_wine_at_rack_location import PlaceWineAtRackLocation
from colosseum.rlbench.tasks.put_money_in_safe import PutMoneyInSafe
from colosseum.rlbench.tasks.reach_and_drag import ReachAndDrag
from colosseum.rlbench.tasks.scoop_with_spatula import ScoopWithSpatula
from colosseum.rlbench.tasks.setup_chess import SetupChess
from colosseum.rlbench.tasks.slide_block_to_target import SlideBlockToTarget
from colosseum.rlbench.tasks.stack_cups import StackCups
from colosseum.rlbench.tasks.straighten_rope import StraightenRope
from colosseum.rlbench.tasks.turn_oven_on import TurnOvenOn
from colosseum.rlbench.tasks.wipe_desk import WipeDesk
